#!/bin/bash
STATE=false
writefile() {
  if [[$STATE]] ; then
    STATE=false
    printf shibs > file;
  else
    STATE=true
    printf larft > file;
  fi
}

while [[ true ]]; do
  writefile
  git add .
  git commit -m 'update'
  git push origin
  sleep 5
done